### ISSUE TITLE
Webhook panic on creation of vsphere MachineDeployment

### ISSUE THREAD

**Issue by heilerich** [kubermatic/machine-controller#1018]
I am unable to create a `MachineDeployment` for vSphere because the webhook process panics with the following error when creating the resource:
<details>
  <summary>Webhook log</summary>

```
W0709 09:39:22.928219       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0709 09:39:22.947681       1 plugin.go:95] looking for plugin "machine-controller-userdata-amzn2"
I0709 09:39:22.947724       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-amzn2"
I0709 09:39:22.947765       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-amzn2'
I0709 09:39:22.947771       1 plugin.go:95] looking for plugin "machine-controller-userdata-centos"
I0709 09:39:22.947783       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-centos"
I0709 09:39:22.947804       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-centos'
I0709 09:39:22.947810       1 plugin.go:95] looking for plugin "machine-controller-userdata-flatcar"
I0709 09:39:22.947821       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-flatcar"
I0709 09:39:22.947842       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-flatcar'
I0709 09:39:22.947851       1 plugin.go:95] looking for plugin "machine-controller-userdata-rhel"
I0709 09:39:22.947861       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-rhel"
I0709 09:39:22.947878       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-rhel'
I0709 09:39:22.947887       1 plugin.go:95] looking for plugin "machine-controller-userdata-sles"
I0709 09:39:22.947897       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-sles"
I0709 09:39:22.947915       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-sles'
I0709 09:39:22.947922       1 plugin.go:95] looking for plugin "machine-controller-userdata-ubuntu"
I0709 09:39:22.947932       1 plugin.go:123] checking "/usr/local/bin/machine-controller-userdata-ubuntu"
I0709 09:39:22.947949       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-ubuntu'
I0709 09:40:16.708924       1 validationwrapper.go:56] Got cache miss for validation
2021/07/09 09:40:16 http: panic serving 10.90.64.0:18258: runtime error: invalid memory address or nil pointer dereference
goroutine 294 [running]:
net/http.(*conn).serve.func1(0xc000337040)
        net/http/server.go:1801 +0x147
panic(0x2cec4c0, 0x52e2290)
        runtime/panic.go:975 +0x3e9
net/http.(*timeoutHandler).ServeHTTP(0xc000696cc0, 0x3881380, 0xc000b82a80, 0xc0008da400)
        net/http/server.go:3277 +0x988
net/http.serverHandler.ServeHTTP(0xc000b82460, 0x3881380, 0xc000b82a80, 0xc0008da400)
        net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000337040, 0x388c600, 0xc000697040)
        net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        net/http/server.go:2969 +0x36c
```

</details>

<details>
  <summary>MachineDeployment resource</summary>

```yaml
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: default-worker
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      machine-type: default-worker
  template:
    metadata:
      labels:
        machine-type: default-worker
    spec:
      versions:
        kubelet: "1.20.8"
      providerSpec:
        value:
          sshPublicKeys:
            - "cert-authority ecdsa-sha2-nistp256 XXX"
            - "ecdsa-sha2-nistp256 XXX"
          operatingSystem: "flatcar"
          operatingSystemSpec:
            distUpgradeOnBoot: false
          cloudProvider: "vsphere"
          cloudProviderSpec:
            username: 
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-vsphere
                key: username
            vsphereURL: 
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-vsphere
                key: vsphereURL
            password:
              secretKeyRef:
                namespace: kube-system
                name: machine-controller-vsphere
                key: password
            datacenter: "DC"
            templateVMName: "k8s-machine-template"
            vmNetName: "NET"
            folder: "KubeOne"
            cluster: "ESXLNX"
            datastoreCluster: "NetApp-Tier2"
            cpus: 4
            memoryMB: 8192
            diskSizeGB: 100
```

</details>

The error message doesn't tell me anything so I can't figure out any way to pinpoint the issue. Increasing the log level on webhook server didn't help either.

I would really appreciate any information on how to figure out what's going on.

Machine controller version: v1.30.0
Deployed by KubeOne: 1.2.3

**Comment by xmudrii** [comment]
@heilerich The reason why you get this error is that the `namespace` field doesn't exist in the `secretKeyRef` object. The machine-controller and machine-controller-webhook Deployments, and the Secret need to be in the same namespace.

The webhook logs are not really useful in this case. We already encountered a similar problem in #1009. We should investigate why this happens.

**Comment by heilerich** [comment]
Thanks for the fast reply. Removing the `namespace` field indeed stops the webhook from crashing, but it still doesn't work, because now I am getting

```
validation failed: failed to create vCenter session: failed vsphere login: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

while 

```
kubectl get secrets -n kube-system machine-controller-vsphere -o jsonpath='{.data.password}' | base64 -d
```

definitely gives me the right credentials. I suspect that the password might be empty now?

I woud also like to add that the official examples do include the `namespace` key

https://github.com/kubermatic/machine-controller/blob/f75f3dfcc7dcd00c28b0b2b50b135a665683cba2/examples/vsphere-machinedeployment.yaml#L48

**Comment by embik** [comment]
I suspect (but haven't confirmed yet) that this might get fixed by #1147, with the `nil` reference being the `context.Context` that is changed in this PR.

**Comment by kron4eg** [comment]
Actually namespace is required for `secretKeyRef` to work:

https://github.com/kubermatic/machine-controller/blob/29140d34e32e88354713725ed72e0feaf09dd080/pkg/providerconfig/types.go#L77-L81

**Comment by kron4eg** [comment]
Yeah, looks like the patch from @embik fixed the secretKeyRef. Just validated with AWS

Such Machine works perfectly fine.
```yaml
  providerSpec:         
    value:             
      cloudProvider: aws                                                       
      cloudProviderSpec:          
        accessKeyId:     
          secretKeyRef:       
            key: AWS_ACCESS_KEY_ID                                             
            name: kubeone-machine-controller-credentials
            namespace: kube-system
        secretAccessKey:
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: kubeone-machine-controller-credentials
            namespace: kube-system
     ...
```
