### ISSUE TITLE
panic on validation step in webhook for machinedeployment.

### ISSUE THREAD

**Issue by sgblv** [kubermatic/machine-controller#1024]
After upgrading to latest 1.27.11 got this error in attempt to create machine-deployment(cloud provider - hetzner)
```
2021/07/20 16:10:42 http: panic serving 10.1.2.3:32616: runtime error: invalid memory address or nil pointer dereference
goroutine 1833 [running]:
net/http.(*conn).serve.func1(0xc0001a9180)
	net/http/server.go:1801 +0x147
panic(0x2ca4be0, 0x5251720)
	runtime/panic.go:975 +0x3e9
net/http.(*timeoutHandler).ServeHTTP(0xc00013fa00, 0x38241c0, 0xc000dce700, 0xc00024d500)
	net/http/server.go:3277 +0x988
net/http.serverHandler.ServeHTTP(0xc0000b01c0, 0x38241c0, 0xc000dce700, 0xc00024d500)
	net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0001a9180, 0x382f300, 0xc00057a3c0)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36c
I0720 16:10:42.969704       1 machines.go:48] Defaulting and validating machine kube-system/
I0720 16:10:42.969795       1 validationwrapper.go:56] Got cache miss for validation
2021/07/20 16:10:42 http: panic serving 10.1.2.3:4615: runtime error: invalid memory address or nil pointer dereference

```
If rewrite this [template]( https://github.com/kubermatic/machine-controller/blob/master/examples/hetzner-machinedeployment.yaml with hetzner api token as plain text - everything work as expected.
)

Is it a bug or examples/ should be fixed?

**Comment by kron4eg** [comment]
duplicate of #943
